name: index.html
favicon: null
layout_spectrum: 0.45650256308726966
typography_spectrum: 0.8128267447464168
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.7950820256955922
  lightness: 0.6222900399006903
  saturation: 0.21604782645590603
  rhythmicContrast: 0.761613851878792
purpose: []
